---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnb-nodejs
resources:
- namespace.yml
- deployment.yml
- service.yml
- ingress.yml
configMapGenerator:
  - name: app
    literals:
      - GREETINGS=Hello world!
