apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-nodejs
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/cnb-nodejs
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  source:
    subPath: .
    git:
      url: https://github.com/alexandreroman/cnb-nodejs
      revision: 4921588e9e67ef1c48571098bd1f5ef9196cbdd6
