apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-springboot
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/cnb-springboot
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  build:
    env:
    - name: BP_JAVA_VERSION
      value: 11.*
  source:
    git:
      url: https://github.com/alexandreroman/cnb-springboot
      revision: 0d5694a3dade6ff79503880919c6aee9e6041c27
