apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-nodejs
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/cnb-nodejs
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  source:
    subPath: .
    git:
      url: https://github.com/alexandreroman/cnb-nodejs
      revision: 0a51f60fb2fe85fc4067276e8992353e5d8c3ea7
