apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: cnb-springboot
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/cnb-springboot
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  build:
    env:
    - name: BP_JAVA_VERSION
      value: 11.*
    - name: BP_MAVEN_BUILT_MODULE
      value: 
  source:
    subPath: .
    git:
      url: https://github.com/alexandreroman/cnb-springboot
      revision: f1ad5900e19f7a23d85aa075dc97058fc7a13024
