apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: linkto-frontend
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/linkto-frontend
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  source:
    subPath: frontend
    git:
      url: https://github.com/alexandreroman/linkto
      revision: ba7f21ac9bc3901444a4d7e3a3f016901fedb301
