apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: linkto-frontend
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/linkto-frontend
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  source:
    subPath: frontend
    git:
      url: https://github.com/alexandreroman/linkto
      revision: f2dc27c73ce5305414d0d1290f18143d0771bbb8
