apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: linkto-backend
  namespace: default
spec:
  tag: harbor.withtanzu.com/tanzu-apps/linkto-backend
  serviceAccount: default
  builder:
    name: default
    kind: ClusterBuilder
  cacheSize: "2Gi"
  build:
    env:
    - name: BP_JAVA_VERSION
      value: 11.*
    - name: BP_MAVEN_BUILT_MODULE
      value: 
  source:
    subPath: backend
    git:
      url: https://github.com/alexandreroman/linkto
      revision: ba7f21ac9bc3901444a4d7e3a3f016901fedb301
