apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:9d5e2f0e043c090e1546987c64a1f62509ed1b7b5d2688ee56aa779282fb95b1
  name: cnb-nodejs
  newName: harbor.withtanzu.com/tanzu-apps/cnb-nodejs
commonAnnotations:
  timestamp: 20200923T150029
resources:
- ../base
