apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3e2f6a0f810f55c74f311ee01f3147a2b32c74c7d98d2e4ba17115d91f9443f7
  name: cnb-nodejs
  newName: harbor.withtanzu.com/tanzu-apps/cnb-nodejs
commonAnnotations:
  timestamp: 20201006T103952
resources:
- ../base
