apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:1629ff1c02f1a37e23044f51d42610e10ba79179411d271041474302ce57d8d1
  name: cnb-springboot
  newName: harbor.withtanzu.com/tanzu-apps/cnb-springboot
commonAnnotations:
  timestamp: 20200923T103533
resources:
- ../base
